### ISSUE TITLE
TODO/FIXME Count 15

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#63]
- [ ] TODO: test w/custom logger that writes to string, not file
       Commit: (ccfc29d) Setup test suite with bedrock-test@4.
       File:  [tests/mocha/test.js:642](https://github.com/digitalbazaar/bedrock/blob/master/tests/mocha/test.js#L642)
       Matthew Collier commented 8 months ago

  - [ ] TODO: add test that adds logger early
       Commit: (ccfc29d) Setup test suite with bedrock-test@4.
       File:  [tests/mocha/test.js:636](https://github.com/digitalbazaar/bedrock/blob/master/tests/mocha/test.js#L636)
       Matthew Collier commented 8 months ago

  - [ ] FIXME: rework this error handling and callers
       Commit: (257fcd7) Use wrapper for loggers.
       File:  [lib/loggers.js:270](https://github.com/digitalbazaar/bedrock/blob/master/lib/loggers.js#L270)
       Dave Longley commented 5 years ago

  - [ ] TODO: run in parallel
       Commit: (749029d) Convert remaining async lib use to promises.
       File:  [lib/loggers.js:202](https://github.com/digitalbazaar/bedrock/blob/master/lib/loggers.js#L202)
       David I. Lehn commented 8 months ago

  - [ ] TODO: simplify with cluster.on('online')?
       Commit: (37cb19c) Add bedrock-cli feature.
       File:  [lib/bedrock.js:509](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L509)
       Dave Longley commented 5 years ago

  - [ ] FIXME: use child logger
       Commit: (c2f318c) Use workaround for master/worker child logger.
       File:  [lib/bedrock.js:452](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L452)
       David I. Lehn commented 7 months ago

  - [ ] TODO: does this need adjusting after fixing the worker `cwd` issue?
       Commit: (3fba9c5) Reorganize code into functions; fix bug with runOnce notifications.
       File:  [lib/bedrock.js:377](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L377)
       Dave Longley commented 5 years ago

  - [ ] FIXME: use child logger
       Commit: (c2f318c) Use workaround for master/worker child logger.
       File:  [lib/bedrock.js:371](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L371)
       David I. Lehn commented 7 months ago

  - [ ] FIXME: v2.0.0: remove warning and default and throw exception .
       Commit: (5f2efcb) Deprecated config.paths defaults.
       File:  [lib/bedrock.js:56](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L56)
       David I. Lehn commented 3 years ago

  - [ ] FIXME: v2.0.0: remove warning and default and throw exception .
       Commit: (5f2efcb) Deprecated config.paths defaults.
       File:  [lib/bedrock.js:43](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L43)
       David I. Lehn commented 3 years ago

  - [ ] FIXME: v2.0.0: remove when removing warnings below.
       Commit: (5f2efcb) Deprecated config.paths defaults.
       File:  [lib/bedrock.js:36](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L36)
       David I. Lehn commented 3 years ago

  - [x] 
       Commit: (8e0950c) Comment out TODO.
       File:  [README.md:715](https://github.com/digitalbazaar/bedrock/blob/master/README.md#L715)
       Dave Longley commented 5 years ago

  - [ ] FIXME also check if a validation type?
       Commit: (7d9c451) Initial commit of bedrock.
       File:  [lib/bedrock/tools.js:110](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock/tools.js#L110)
       Dave Longley commented 6 years ago

  - [ ] * TODO: look into better stack parsing libraries.
       Commit: (4d3fafd) Parse stack errors.
       File:  [lib/bedrock/tools.js:76](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock/tools.js#L76)
       David I. Lehn commented 6 years ago

  - [ ] FIXME: add parse error handling
       Commit: (4d3fafd) Parse stack errors.
       File:  [lib/bedrock/tools.js:98](https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock/tools.js#L98)
       David I. Lehn commented 6 years ago

**Comment by dlongley** [comment]
Closing -- all TODOs/FIXMEs have been assigned specific issues and those issues are linked to in source.
